### ISSUE TITLE
Electric potential always 0

### ISSUE THREAD

**Issue by henrikjaerleblad** [JuliaFusion/Equilibrium.jl#4]
This is not really an issue, but more a highlight of the fact that, regardless of the user working with an EFITEquilibrium or a SolovevEquilibrium, the electric potential will always be zero when using the Equilibrium.jl package.

For EFIT equilibria, the electric potential is computed from the poloidal current multiplied by 0 (in efit_io.jl), as shown below:
![Capture](https://user-images.githubusercontent.com/38374661/212861403-a4ec26d0-93f0-47eb-ad5b-e30f8295c050.PNG)

For Solov'ev equilibria, the electric_potential function is defined using the zero()-function (in solovev.jl), as shown below:
![Capture2](https://user-images.githubusercontent.com/38374661/212861721-0629b1d8-3134-40dd-8a4f-55bf93e30e0d.PNG)

**Comment by henrikjaerleblad** [comment]
Should we do something about this?

**Comment by henrikjaerleblad** [comment]
Related to this, in the GuidingCenterOrbits.jl package, the HamiltonianCoordinate function uses the electric_potential() function to compute the total energy (kinetic+potential), as shown below:
![Capture](https://user-images.githubusercontent.com/38374661/212862728-33610a89-55a8-4462-9d1f-7da32989aa33.PNG)

Thus, if the user is unaware of this issue and only looking at the code in GuidingCenterOrbits.jl, they might assume that the function electric_potential() is able to return non-zero values. Which it is not at the moment

**Comment by lstagner** [comment]
The electric potential is not available in the standard EFIT gfile since the electric field isn't included in the Grad-Shafranov solution.

You can get the electric potential from TRANSP if you use the following:

https://github.com/JuliaFusion/Equilibrium.jl/blob/07a510679a8e670f4fac40b17509e6168a578450/src/transp_io.jl#L3-L13
