### ISSUE TITLE
cubic_spline_interpolation

### ISSUE THREAD

**Issue by henrikjaerleblad** [JuliaFusion/Equilibrium.jl#5]
I think the Julia packages have been upgraded so that we cannot use the same cubic spline syntax anymore? I am currently investigating how to best solve the issue.

![pastedImage](https://user-images.githubusercontent.com/38374661/235644140-8e6ad575-1155-4151-b3ea-cbac491c0fa6.png)

**Comment by lstagner** [comment]
Thats strange. Did the `using Interpolations` call not export the convenience constructors.

**Comment by henrikjaerleblad** [comment]
Solved. Needed to upgrade Interpolations package to latest version.
