### ISSUE TITLE
cocos.jl in a separate package?

### ISSUE THREAD

**Issue by mgalenb** [JuliaFusion/Equilibrium.jl#7]
ive been thinking about using your cocos.jl code in a package I am working on. have you considered factoring it out into a separate package? perhaps up to the GEQDSK file interface?

**Comment by lstagner** [comment]
We actually have a seperate repo for it for a private project. I'll have to ask if we can make it public.

**Comment by mgalenb** [comment]
ok no problem. I think it would be useful for other groups

**Comment by lstagner** [comment]
I talked with the main guy in charge and he made the repo public. https://github.com/ProjectTorreyPines/CoordinateConventions.jl
